### ISSUE TITLE
LateInitializationError: Local 'bestMatch' has not been initialized.

### ISSUE THREAD

**Issue by oikkoikk** [amake/dynamic-fonts-flutter#4]
```
LateInitializationError: Local 'bestMatch' has not been initialized.
```

Hi. I have an error with bestMatch late initialization with Flutter 3.19.1, Dart 3.3.0.

**Comment by amake** [comment]
I need more information. What is the stack trace? Have you called `DynamicFonts.register` before that point? What did you provide to `DynamicFonts.register`?

**Comment by amake** [comment]
I think the problem is with your registration call for PartialSans. The `fold` doesn't add anything to the accumulator. If you make it match the `fold` call for Pretendard then it should work.

**Comment by oikkoikk** [comment]
but I don't have more variants in PartialSans. I have PartialSans-Regular only.

**Comment by amake** [comment]
You have one variant, but you're supplying an empty variant map (i.e. zero variants). Yes, you should make it like Pretendard.

**Comment by oikkoikk** [comment]
Thank you! I'll try it.
